apiVersion: v2
name: url-datadog-monitor
description: A Helm chart for deploying URL Datadog Monitor on Kubernetes
type: application
version: 0.0.1
appVersion: "0.0.1"
home: https://github.com/kuskoman/url-datadog-monitor
sources:
  - https://github.com/kuskoman/url-datadog-monitor
maintainers:
  - name: kuskoman
    url: https://github.com/kuskoman
keywords:
  - monitoring
  - datadog
  - url-monitor
  - kubernetes-operator
